### ISSUE TITLE
Typescript support monorepo broke with PR #23

### ISSUE THREAD

**Issue by entropitor** [haydenmeade/neotest-jest#29]
https://github.com/haydenmeade/neotest-jest/pull/23 broke the typescript support for my setup 😅 More specifically https://github.com/haydenmeade/neotest-jest/pull/23/files#diff-13047bd2b66848e27a90278d4ec653631a1ccddd605e47f618391276bc47165bR176

Should this maybe be an option settable by the user? Because I see that other users have problems if it's not set...

**Comment by stevearc** [comment]
When you say "broke", what is the actual effect that you're seeing? The adapter root should be finding the nearest directory to the path that contains a `package.json` file. How is your project laid out, and what directory do you have vim open in?

We could put this behavior behind an option, but I'd like to know what exactly is going wrong first because there may be better solutions.

**Comment by entropitor** [comment]
I have vim open at the git root of my project, which contains a subdirectory `apps` and per app there is a new directory with some code that's self-contained but uses a shared tsconfig.json etc. 

And I'm seeing the same things as https://github.com/mxsdev/nvim-dap-vscode-js/issues/5#event-7109749546. Maybe because babel stuff is configured globally, not per app?

I'm not sure what the previous working directory is but maybe it was running from the root (finding babel) and now it runs from the app subdirectory (and it doesn't find it)? Or vice versa

**Comment by stevearc** [comment]
The previous working directory was whatever `:echo getcwd()` is in vim, so likely the root.

So the `apps/*` directories _do_ contain a `package.json` file (because they're matching the root pattern), but you still want the jest command to be run from your current directory which is the root? If that's the case then yeah, I think the best thing to do would be to add a config option.
